#!/usr/bin/env python3
"""One-time, offline import of the two existing baselines. Not a dataset builder."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import office  # project dependency bootstrap
from office_trace_bench.contracts import sha256, read_json, write_json
from office_trace_bench.workbooks import workbook_snapshot


def main():
    import shutil
    from openpyxl import load_workbook
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, required=True, help='Explicit historical source; never required by tests')
    source = parser.parse_args().source.resolve()
    if (ROOT / 'datasets/xlsx/tlc/manifest.json').exists():
        raise SystemExit('baseline manifests already exist; refusing to replace the frozen import')
    for kind in ('xlsx', 'pdf'):
        shutil.copytree(source / 'cases' / kind / 'output', ROOT / 'legacy' / kind / 'output')
        # These are explicitly historical traces, not traces generated by this project.
        for filename in ('openclaw_session.jsonl', 'trajectory.json'):
            shutil.copy2(source / 'cases' / kind / 'agent_run' / filename,
                         ROOT / 'legacy' / kind / filename)
    tlc = ROOT / 'datasets/xlsx/tlc'
    book = load_workbook(tlc / 'input/monthly_operations_template.xlsx')
    baseline = workbook_snapshot(book, ['Raw_Sample'])
    book.close()
    import gc
    del book
    gc.collect()
    output = load_workbook(ROOT / 'legacy/xlsx/output/monthly_operations_report.xlsx', read_only=True, data_only=True)
    values = {cell: output['Executive_Summary'][cell].value for cell in ('B5', 'B6', 'B7', 'B8', 'B9', 'B13', 'B14', 'B15', 'B16')}
    output.close()
    write_json(tlc / 'expected.json', {'baseline': baseline, 'cached_values': values,
               'oracle_provenance': 'Input structure and previously accepted legacy output; not generated by the new Agent.'})
    metrics = [
        {'name': 'Total Trips', 'cell': 'B5', 'required_references': ['Reconciliation!B10'], 'number_format': '#,##0', 'font_color': '008000'},
        {'name': 'Total Fare Revenue', 'cell': 'B6', 'required_references': ['Reconciliation!B14'], 'number_format': '$#,##0.00', 'font_color': '008000'},
        {'name': 'Overall Average Fare', 'cell': 'B7', 'required_references': ['Hourly_Summary!B34'], 'number_format': '$#,##0.00', 'font_color': '008000'},
        {'name': 'Removal Rate', 'cell': 'B8', 'required_references': ['Reconciliation!B5'], 'number_format': '0.0%', 'font_color': '008000'},
        {'name': 'Reconciliation Status', 'cell': 'B9', 'required_references': ['Reconciliation!B24', 'Reconciliation!B25'],
         'meaning': 'PASS only when both source cells equal YES - Consistent; otherwise REVIEW'},
    ]
    manifest = {
        'schema_version': 'office-dataset-v1', 'dataset_id': 'tlc', 'kind': 'xlsx',
        'domain': 'transportation_operations', 'task': 'Enhance the existing NYC TLC January 2024 operations workbook',
        'workbook': 'monthly_operations_template.xlsx', 'output_workbook': 'monthly_operations_report.xlsx',
        'requirements': {
            'summary_sheet': 'Executive_Summary', 'base_sheets': baseline['sheet_order'], 'raw_sheets': ['Raw_Sample'],
            'minimum_bytes': 10000000, 'minimum_formula_count': 45, 'metrics': metrics,
            'scenario': {'selector_cell': 'B12', 'default': 'Base',
                'rows': [{'name': 'Base', 'cells': {'D13': 'Base', 'E13': 1.0, 'F13': 1.0}},
                         {'name': 'Upside', 'cells': {'D14': 'Upside', 'E14': 1.08, 'F14': 1.05}},
                         {'name': 'Downside', 'cells': {'D15': 'Downside', 'E15': .93, 'F15': .95}}],
                'table_columns': {'D': 'Scenario', 'E': 'Fare multiplier', 'F': 'Trip multiplier'},
                'formula_metrics': [
                    {'name': 'Selected Fare Multiplier', 'cell': 'B13', 'required_references': ['B12'], 'meaning': 'Look up the fare multiplier for the selected scenario', 'font_color': '000000'},
                    {'name': 'Selected Trip Multiplier', 'cell': 'B14', 'required_references': ['B12'], 'meaning': 'Look up the trip multiplier for the selected scenario'},
                    {'name': 'Projected Trips', 'cell': 'B15', 'required_references': ['B5', 'B14'], 'meaning': 'Total trips multiplied by selected trip multiplier'},
                    {'name': 'Projected Fare Revenue', 'cell': 'B16', 'required_references': ['B6', 'B13', 'B14'], 'meaning': 'Total fare multiplied by selected fare and trip multipliers'}]},
            'charts': [{'id': 'daily_trips', 'description': 'Daily trip trend', 'required_references': ['Daily_Summary!']},
                       {'id': 'payment_mix', 'description': 'Payment method mix', 'required_references': ['Payment_Summary!']}],
            'minimum_conditional_formats': 2, 'minimum_comments': 2, 'recalc_timeout': 180,
            'styling': 'Arial, blue/gray visual hierarchy; editable constants blue, cross-sheet formulas green, local formulas black'},
        'publish_files': [{'input': 'prepared_monthly_operations_summary.csv', 'output': 'monthly_operations_summary.csv', 'sha256': sha256(tlc / 'input/prepared_monthly_operations_summary.csv')},
                          {'input': 'prepared_reconciliation_summary.csv', 'output': 'reconciliation_summary.csv', 'sha256': sha256(tlc / 'input/prepared_reconciliation_summary.csv')}],
        'required_outputs': ['monthly_operations_report.xlsx', 'monthly_operations_summary.csv', 'reconciliation_summary.csv', 'formula_recalc.json', 'business_verification.json', 'xlsx_enhancement_summary.json'],
        'trace_rules': [{'pattern': r'office\.py\s+verify', 'operation': 'verify_business'},
                        {'pattern': r'recalc\.py', 'operation': 'recalculate_formulas'},
                        {'pattern': r'\bcp\b.*\.csv', 'operation': 'publish_csv'},
                        {'pattern': r'load_workbook', 'operation': 'inspect_workbook'}],
    }
    finalize(tlc, manifest)
    opm = ROOT / 'datasets/pdf/opm'
    sys.path.insert(0, str(ROOT / 'vendor/skills/pdf/scripts'))
    from pypdf import PdfReader
    from extract_form_field_info import get_field_info
    from importlib.util import spec_from_file_location, module_from_spec
    spec = spec_from_file_location('legacy_pdf_verifier', ROOT / 'legacy/pdf/verify_pdf_batch.py')
    legacy = module_from_spec(spec)
    spec.loader.exec_module(legacy)
    no_fields = sorted(legacy.SHARED_NO_FIELDS)
    protected = sorted(legacy.SENSITIVE_FIELDS)
    rules = [
        {'semantic': 'full_name', 'field_id': 'Full Name', 'value_from': 'full_name'},
        {'semantic': 'birthplace', 'field_id': 'PLACE OF BIRTH Include city and state or country', 'value_from': 'place_of_birth'},
        {'semantic': 'birthdate', 'field_id': 'DATE OF BIRTH MM  DD  YYYY', 'value_from': 'date_of_birth'},
        {'semantic': 'phone', 'field_id': 'Day', 'value_from': 'day_phone'},
        {'semantic': 'other_names', 'field_id': 'Other Names Used 2', 'value_from': 'other_names'},
        {'semantic': 'citizenship_country', 'field_id': 'Country of Citizenship', 'constant': 'United States'},
        {'semantic': 'citizenship', 'field_id': 'Are you a U.S. Citizen?', 'value_from': 'us_citizen', 'choices': {'true': '/Yes', 'false': '/No'}},
        {'semantic': 'selective_service_eligibility', 'field_id': 'Male', 'value_from': 'born_male_after_1959', 'choices': {'true': '/Yes', 'false': '/No'}},
        {'semantic': 'selective_service_registration', 'field_id': 'Have you registered with Selective Service', 'value_from': 'registered_selective_service', 'choices': {'true': '/Yes', 'false': '/No'}},
        {'semantic': 'continuation', 'field_id': 'Continuation of Space or Agency Specific Questions', 'source': 'shared', 'value_from': 'shared_answers.continuation'},
        *[{'semantic': 'shared_background_' + str(i), 'field_id': field, 'constant': '/No'} for i, field in enumerate(no_fields)],
    ]
    reader = PdfReader(opm / 'input/of306_aug2023.pdf')
    summary = {'input_form': 'of306_aug2023.pdf', 'applicant_count': 10, 'filled_pdf_count': 10,
               'rendered_page_count': 33, 'ssn_and_signatures_left_blank': True}
    write_json(opm / 'expected.json', {'summary_values': summary,
               'oracle_provenance': 'Frozen synthetic records and OPM rules imported from the existing case.'})
    manifest = {
        'schema_version': 'office-dataset-v1', 'dataset_id': 'opm', 'kind': 'pdf', 'domain': 'employment_forms',
        'task': 'Inspect, batch-fill, render and verify OPM OF-306 using synthetic training applicants',
        'form': 'of306_aug2023.pdf', 'records': 'synthetic_applicants.json', 'records_key': 'applicants',
        'requirements': {'page_count': len(reader.pages), 'field_count': len(get_field_info(reader)),
            'record_count': 10, 'field_rules': rules, 'protected_blank': protected,
            'minimum_pdf_bytes': 100000, 'minimum_png_bytes': 10000,
            'visible_changes': [{'page': 2, 'minimum_changed_pixels': 500, 'pixel_threshold': 12}]},
        'summary_contract': {**summary, 'fill_script_invocations': 10, 'render_script_invocations': 11},
        'required_outputs': ['check_fillable_fields.log', 'form_field_info.json', 'field_values', 'filled', 'rendered', 'batch_summary.json', 'business_verification.json'],
        'trace_rules': [{'pattern': r'office\.py\s+verify', 'operation': 'verify_business'},
                        {'pattern': r'check_fillable_fields\.py', 'operation': 'check_fillability'},
                        {'pattern': r'extract_form_field_info\.py', 'operation': 'extract_field_schema'},
                        {'pattern': r'fill_fillable_fields\.py', 'operation': 'fill_form'},
                        {'pattern': r'convert_pdf_to_images\.py', 'operation': 'render_pdf'}],
    }
    finalize(opm, manifest)
    write_json(ROOT / 'legacy/archive_manifest.json', {'source_project': str(source), 'execution': 'historical-import',
        'files': {str(p.relative_to(ROOT)): sha256(p) for p in (ROOT / 'legacy').rglob('*') if p.is_file() and p.name != 'archive_manifest.json'}})
    print('TLC/OPM frozen manifests and historical regression fixtures imported')


def finalize(directory, manifest):
    manifest.update(input_files={str(p.relative_to(directory)): sha256(p) for p in (directory / 'input').rglob('*') if p.is_file()},
                    expected_file='expected.json', expected_sha256=sha256(directory / 'expected.json'))
    write_json(directory / 'manifest.json', manifest)


if __name__ == '__main__':
    main()
